def test_challenge31_copart_honda_search(py):
    py.visit('https://copart.com')
    py.get('[data-uname="homePageFindAVehicle"]').click()
    py.get('[data-uname="vehicleFinderTab"]').click()
    py.get("[data-uname=\"vehiclefinderTypedropdownbox\"]").select('Automobile')
    py.get('[data-uname="vehiclefinderMakedownbox"]').select('Honda')
    py.get('[data-uname="vehiclefinderModeldownbox"]').select('CRV')
    py.get('[data-uname="vehiclefinderLocationdropdownbox"]').select('NY - Long Island')
    py.get('[ng-click="search(form)"]').click()
    assert py.should().contain_title('Honda')
    py.get('[name="serverSideDataTable_length"]').select('100').click()
